# -*- coding: utf-8 -*-
"""Test Project  - Delivery Tracker App(Using Steamlit Cloud)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FeRy2BSZcLajPd1f9SgHMF42CWAcgraU
"""

# ==============================================================
# 🌐 LIVE DASHBOARD: Block-wise Anganwadi Count (by Project)
# Technologies: Dash + Plotly + Google Sheets (Live Data)
# Ready for Deployment on Render / Railway / HuggingFace / etc.
# ==============================================================

import pandas as pd
import dash
from dash import dcc, html, Input, Output
import plotly.express as px
from flask import Flask

# ---- Step 1: Flask + Dash setup ----
server = Flask(__name__)
app = dash.Dash(__name__, server=server)

# ---- Step 2: Initial Load ----
sheet_url = "https://docs.google.com/spreadsheets/d/1kF3fdOX3hIBGczBJ5COMvZ_lmRO-ULLQuZkxe0B2haU/export?format=csv"
df = pd.read_csv(sheet_url)
df.columns = df.columns.str.strip()

# ---- Step 3: Layout ----
app.layout = html.Div(
    style={
        "backgroundColor": "#F9FAFB",
        "fontFamily": "Quicksand, sans-serif",
        "padding": "20px",
        "maxWidth": "900px",
        "margin": "auto",
        "boxShadow": "0px 0px 10px rgba(0,0,0,0.1)",
        "borderRadius": "15px"
    },
    children=[
        html.H2("📊 Anganwadi Dashboard", style={"textAlign": "center", "color": "#2E3A87"}),

        html.Label("Select Project:", style={"fontWeight": "bold", "marginTop": "15px"}),

        dcc.Dropdown(
            id="project_filter",
            options=[{"label": p, "value": p} for p in sorted(df["Project"].unique())],
            value=sorted(df["Project"].unique())[0],
            clearable=False,
            style={"backgroundColor": "white", "color": "#2E3A87"}
        ),

        html.Br(),

        dcc.Graph(id="bar_chart", style={"borderRadius": "10px"})
    ]
)

# ---- Step 4: Callback (fetches fresh data dynamically) ----
@app.callback(
    Output("bar_chart", "figure"),
    Input("project_filter", "value")
)
def update_chart(selected_project):
    # 🔁 Load fresh data each time
    sheet_url = "https://docs.google.com/spreadsheets/d/1kF3fdOX3hIBGczBJ5COMvZ_lmRO-ULLQuZkxe0B2haU/export?format=csv"
    df = pd.read_csv(sheet_url)
    df.columns = df.columns.str.strip()

    # Filter & aggregate
    filtered = df[df["Project"] == selected_project]
    block_counts = filtered.groupby("Block")["Anganwadi"].count().reset_index()
    block_counts = block_counts.sort_values("Anganwadi", ascending=False)

    # Plotly chart
    fig = px.bar(
        block_counts,
        x="Anganwadi",
        y="Block",
        orientation="h",
        title=f"Block-wise Anganwadi Count for '{selected_project}'",
        text="Anganwadi",
        color="Anganwadi",
        color_continuous_scale="Blues"
    )

    fig.update_layout(
        title_font=dict(size=20, color="#2E3A87"),
        xaxis_title="Count of Anganwadis",
        yaxis_title="Block",
        plot_bgcolor="white",
        paper_bgcolor="white",
        font=dict(size=13),
        margin=dict(l=80, r=40, t=80, b=60),
        coloraxis_showscale=False
    )
    fig.update_traces(textposition="outside")

    return fig


# ---- Step 5: Run app ----
if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8050)